# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L091BB4hqjkjgbrRYMw6YcF5cYBb6tGf
"""

import tensorflow_datasets as tfds
import matplotlib.pyplot as plt

dataset, info = tfds.load("mnist", with_info=True, as_supervised=True)
mnist_train, mnist_test = dataset["train"], dataset["test"]

info

def show_batch(images, labels):
  plt.figure(figsize=(12,12))
  for i in range(12):
    ax = plt.subplot(4,3,i+1)
    plt.imshow(images[i].numpy().astype("uint8"))
    plt.title(str(labels[i].numpy()))
    plt.axis("off")
  plt.show()

i =0
for image , label in mnist_train.batch(32).take(5):
  i = i +1
  show_batch(image, label)

import tensorflow as tf
from tensorflow.keras import layers, models

model = models.Sequential([
    layers.Conv2D(32, (3,3), activation='relu', input_shape=(28,28,1)),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Flatten(),
    layers.Dense(64 , activation='relu'),
    layers.Dense(10, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

import numpy as np

X_train =  []
y_train = []

for img , label in tfds.as_numpy(mnist_train):
  X_train.append(img)
  y_train.append(label)
X_train = np.array(X_train)
y_train = np.array(y_train)

import numpy as np

x_test = []
y_test = []

for img, label in tfds.as_numpy(mnist_test):
    x_test.append(img)
    y_test.append(label)

x_test = np.array(x_test)
y_test = np.array(y_test)

model.fit( X_train , y_train, epochs=5 , validation_split=0.1 )

model.save("mnist_model.keras")